### ISSUE TITLE
[PR #32] <MenuItemLink>의 leftIcon 속성 관련 버그

### ISSUE THREAD

**Issue by yypp1226** [ucharles/Comrade#33]
## 현상
#32
`<MenuItemLink>`의 `leftIcon` 속성에는 `<svgIcon>`만 사용 가능.

현재 `<MenuItemLink>`로 Calendar의 메뉴를 구성하고 있는데,
`leftIcon`에  `<Avartar>`를 설정할 시, 아래의 에러 내용이 표시됨.
화면 표시에는 문제가 없어보이나, 향후 버그를 일으킬 가능성 존재.
 
참고
https://github.com/marmelab/react-admin/issues/1926

## 에러 내용
```
bundle.js:134227 Warning: React does not recognize the `titleAccess` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `titleaccess` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at http://localhost:3000/static/js/bundle.js:5248:66
    at Avatar (http://localhost:3000/static/js/bundle.js:31710:82)
    at div
    at http://localhost:3000/static/js/bundle.js:5248:66
    at ListItemIcon (http://localhost:3000/static/js/bundle.js:46031:82)
    at a
    at LinkWithRef (http://localhost:3000/static/js/bundle.js:172546:5)
    at http://localhost:3000/static/js/bundle.js:5248:66
    at ButtonBase (http://localhost:3000/static/js/bundle.js:33041:82)
    at http://localhost:3000/static/js/bundle.js:5248:66
    at MenuItem (http://localhost:3000/static/js/bundle.js:47216:83)
    at http://localhost:3000/static/js/bundle.js:5248:66
    at http://localhost:3000/static/js/bundle.js:122150:16
    at div
    at http://localhost:3000/static/js/bundle.js:5248:66
    at div
    at http://localhost:3000/static/js/bundle.js:5248:66
    at div
    at http://localhost:3000/static/js/bundle.js:5248:66
    at Transition (http://localhost:3000/static/js/bundle.js:174334:30)
    at Collapse (http://localhost:3000/static/js/bundle.js:36174:82)
    at div
    at http://localhost:3000/static/js/bundle.js:5248:66
    at Menu (http://localhost:3000/static/js/bundle.js:122574:67)
    at div
    at MyMenu (http://localhost:3000/static/js/bundle.js:2813:74)
    at div
    at div
    at http://localhost:3000/static/js/bundle.js:5248:66
    at Paper (http://localhost:3000/static/js/bundle.js:48973:82)
    at http://localhost:3000/static/js/bundle.js:5248:66
    at div
    at http://localhost:3000/static/js/bundle.js:5248:66
    at Drawer (http://localhost:3000/static/js/bundle.js:38448:83)
    at http://localhost:3000/static/js/bundle.js:5248:66
    at Sidebar (http://localhost:3000/static/js/bundle.js:122458:15)
    at main
    at div
    at div
    at http://localhost:3000/static/js/bundle.js:5248:66
    at Layout (http://localhost:3000/static/js/bundle.js:122751:13)
    at MyLayout
    at div
    at Routes (http://localhost:3000/static/js/bundle.js:173701:5)
    at CoreAdminRouter (http://localhost:3000/static/js/bundle.js:114499:11)
    at Routes (http://localhost:3000/static/js/bundle.js:173701:5)
    at CoreAdminUI (http://localhost:3000/static/js/bundle.js:114564:15)
    at AdminUI
    at Router (http://localhost:3000/static/js/bundle.js:173634:15)
    at HistoryRouter (http://localhost:3000/static/js/bundle.js:112316:15)
    at TranslationProvider (http://localhost:3000/static/js/bundle.js:114289:19)
    at QueryClientProvider (http://localhost:3000/static/js/bundle.js:169191:21)
    at Provider (http://localhost:3000/static/js/bundle.js:169884:20)
    at CoreAdminContext (http://localhost:3000/static/js/bundle.js:114310:19)
    at InnerThemeProvider (http://localhost:3000/static/js/bundle.js:66153:70)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:64996:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:66173:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:123094:15)
    at AdminContext (http://localhost:3000/static/js/bundle.js:132897:12)
    at Admin (http://localhost:3000/static/js/bundle.js:132921:16)
    at App
    at AuthContextProvider (http://localhost:3000/static/js/bundle.js:3241:70)
```

**Comment by ucharles** [comment]
#37 적용 후 해당 에러 메시지가 출력되지 않는 것을 확인.

**Comment by ucharles** [comment]
#37 이 적용된 #36 머지 완료. Close 하겠습니다.
